# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Be a part of the conversation about relevant issues in Toronto.
baseurl: "/MyDem0cracy.ca-site" # the subpath of your site, e.g. /blog
url: "linamnt.github.io" # the base hostname & protocol for your site
twitter_username:
github_username:  CivicTechTO/vToronto

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
disqus_shortname:
# Disabled because trial is over.
livechat_license: null

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->

# Set this to override the official embed code with a custom one
# We use rawgit.com: https://stackoverflow.com/questions/17341122/link-and-execute-external-javascript-file-hosted-on-github
# This prevents errors about mime type where browser fails to execute script
polis_embed_url: https://cdn.rawgit.com/patcon/polisClientParticipation/customize-padding/api/embed.js

collections:
  faqs:
    # Prevents Jekyll from creating page for each item.
    # We just want the listing page.
    output: false


defaults:
  - scope:
      type: faqs
    values:
      date_added: 2016-12-08

# Used to render to proper text/config in language-specific branches
locale: en

locales:
  en:
    site:
      title: vToronto.ca
      host: vToronto.ca
    #google_analytics: UA-77242163-1
    #polis_conversation_id: 5mnfxu85hx
    #change_locale_text: Français
    #change_locale_url: https://mydem0cratie.ca
    methodology: |
      ### Seed comments

      We setup the initial consultation process with a set of seed comments to kick-start the conversation. These seed comments were derived from statements mentioned in the MPs reports from their respective town hall meetings on electoral reform which can be found [here](http://www.parl.gc.ca/Content/HOC/Committee/421/ERRE/WebDoc/WD8405589/Members_Reports-e.html).

      ### How commenting works

      We invite you to share your own perspectives. Once you have expressed your agreement/disagreement or passed on all statements, feel free to submit a statement of your own if you feel that it is an essential piece to the national conversation about electoral reform.

      ### Why moderate the conversation?

      We are using a moderation process where all comments will first be approved before being visible to other visitors of mydem0cracy.ca. We are using this moderation process to reduce repetitive statements and to assure all statements are relevant to the conversation. We will release all submitted statements as part of our open data policy in order to be as transparent as possible about how statements were moderated. (We are [working on making this more real-time](https://github.com/CivicTechTO/MyDem0cracy.ca-site/issues/12).)

    about: |
      A healthy democracy requires that Governments listen to citizens in order to make better decisions. This initiative aims to hear from as many Canadians as possible in a national conversation on electoral reform.

      Our approach will collect our voices in a real-time, coherent and open ended way while allowing you to agree/disagree or pass on what others have already said. We hope to provide a greater ability to listen to the diversity of opinions across the country while avoiding the echo chambers of typical social media engagement.

      The goal of this parallel public consultation process is to have a large-scale conversation where participants can listen, share and learn from others’ viewpoints. We hope the debate evolves in such a way such that consensus statements allow this conversation to move forward in a productive and actionable way.

      Basically, we'd like to build consensus through conversation rather than continue to yell at each other from across the table.
    intro: |
      Welcome to the vToronto website where public consultations on issues relevant to citizens of Toronto will be held.




  fr:
    site:
      title: vToronto.ca
      host: vToronto.ca
#    google_analytics: UA-77242163-2
#    polis_conversation_id: 4h8wyzbbca
    change_locale_text: English
#    change_locale_url: https://mydem0cracy.ca
    methodology: |
      foobar
    about: |
      foobar
